export const topProjects = [
  {
    // videoSrc: 'echo-chat-AB1zhCP8soPOmnJJP7Fho36VpJgaFg.mp4',
    imageSrc: '/img1a.png',
    title: 'GokulPG',
    tags: [
      'Reactjs',
      'Express',
      'Mongo DB',
      'Firebase',
      'Nodejs',
      'TailwindCSS',
      'Vercel',
    ],
    timeline: 'Nov 2024 - Dec 2024',
    tagline: 'PG service website for freelance client',
    sourceCodeHref: 'https://github.com/DronKashyap/GokulPG-Frontend',
    liveDemoHref: 'https://gokulpg.com/',
  },

  {
    // videoSrc: 'space-uecizlixlpcAH1cmch9kYp12JQ0ryA.mp4',
    imageSrc: '/img3a.png',
    title: 'Envy-Attire',
    tags: [
      'Typescript',
      'Nextjs',
      'NextAuth',
      'Prisma',
    ],
    timeline: 'Aug 2024',
    tagline: 'Clothes e-commerce website',
    sourceCodeHref: 'https://github.com/DronKashyap/EnvyAttire',
    liveDemoHref: 'https://envy-attire.vercel.app/',
  },
  {
    imageSrc: '/img2a.png',
    title: 'DK Property Listings',
    // videoSrc: 'fitflow-bxeIZzEYBBHqSqXUEa1ivzKo4Jq8Ck',
    tags: [
      'Typescript',
      'Prisma',
      'PostgreSQL',
      'Firebase',
      'TailwindCSS',
      'ExpressJS',
    ],
    timeline: 'Jun 2024 - July 2024',
    tagline: 'Property listing website ',
    sourceCodeHref: 'https://github.com/DronKashyap/DK-PropertyListings',
    liveDemoHref: 'https://dk-property-listings.vercel.app/',
  },
  {
    // videoSrc: 'githubtimeline-PxWo4wrOFHi71ER3DdFrN1C8U2D0zE.mp4',
    imageSrc: '/img4a.png',
    title: 'iPhone 15',
    tags: ['Reactjs', 'GSAP', 'Three.JS', 'React-3-Fiber', 'TailwindCSS'],
    timeline: 'July 2024',
    tagline: 'iPhone 15 3D landing page',
    sourceCodeHref: 'https://github.com/DronKashyap/3D-IphoneLandingPage',
    liveDemoHref: 'https://3d-iphone-landing-page.vercel.app/',
  },
  {
    // videoSrc: 'hikari-ya72znzpdAcgxLkGN3GhrKbeUVLx1z.mp4',
    imageSrc: '/img5a.png',
    title: 'Fizzi',
    tags: [
      'Reactjs', 'GSAP', 'Three.JS', 'React-3-Fiber', 'TailwindCSS', 'Zustand',
    ],
    timeline: 'May 2024',
    tagline: 'Soda Commercial Landing Page.',
    sourceCodeHref: 'https://github.com/DronKashyap/Soda-Landing-Page',
    liveDemoHref: 'https://fizzi.vercel.app/',
  },
]
